import FormField from "@/components/FormField";
import Container from "@/components/global/Container";
import Layout from "@/components/global/Layout";
import ImageCard from "@/components/ImageCard";
import axios from "axios";
import Head from "next/head";
import { useState } from "react";

export async function getServerSideProps(context) {
  const { data } = await axios.get(`${process.env.API_BASE_URL}/api/v1/posts`);

  return {
    props: {
      data: data.data,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const [searchQuery, setSearchQuery] = useState("");
  const handleChange = (e) => setSearchQuery(e.target.value);

  const filteredData = (data, searchQuery) => {
    return data.filter((image) => {
      return (
        image.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        image.prompt.toLowerCase().includes(searchQuery.toLowerCase())
      );
    });
  };
  return (
    <>
      <Head>
        <title>Samba Ai - An image generating website using Dalle-E api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <section className="py-12">
          <Container>
            <div>
              <h1 className="font-extrabold text-[#222328] text-[32px] capitalize">
                Generate image with text
              </h1>
              <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
                Browse through a collection of imaginative and visually stunning
                images using dalle-e api generated by random people in the
                internet
              </p>

              <div className="mt-5">
                <FormField
                  id={"name"}
                  label={""}
                  name={"name"}
                  placeholder={"Search by prompt or name"}
                  handleChange={handleChange}
                  type="text"
                  value={searchQuery}
                />
              </div>
            </div>

            <div className="mt-16 grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
              {filteredData(props.data, searchQuery).map((image) => (
                <ImageCard
                  key={image._id}
                  _id={image._id}
                  name={image.name}
                  prompt={image.prompt}
                  photo={image.photo}
                />
              ))}
            </div>
          </Container>
        </section>
      </Layout>
    </>
  );
}
