import Container from "@/components/global/Container";
import Layout from "@/components/global/Layout";
import ImageCard from "@/components/ImageCard";
import axios from "axios";
import Head from "next/head";
import Masonry from "react-masonry-css";

export async function getServerSideProps(context) {
  const { data } = await axios.get(`http://localhost:8080/api/v1/posts`);
  console.log(data);

  return {
    props: {
      data: data.data,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const breakpointColumnsObj = {
    default: 4,
    1100: 3,
    700: 2,
    500: 1,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="py-12">
          <Container>
            <div>
              <h1 className="font-extrabold text-[#222328] text-[32px]">
                The Community Showcase
              </h1>
              <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
                Browse through a collection of imaginative and visually stunning
                images generated by Samba AI
              </p>
            </div>

            <div className="mt-16 grid grid-cols-3 gap-10">
              {/* <Masonry
                breakpointCols={3}
                className="my-masonry-grid"
                columnClassName="my-masonry-grid_column"
              > */}
              {props.data.map((image) => (
                <ImageCard
                  key={image._id}
                  _id={image._id}
                  name={image.name}
                  prompt={image.prompt}
                  photo={image.photo}
                  // className="h-96"
                />
              ))}
              {/* </Masonry> */}
            </div>
          </Container>
        </section>
      </Layout>
    </>
  );
}
