"use client";
import React, { useState } from "react";
import ImageCard from "@/components/ImageCard";
import axios from "axios";
import Container from "@/components/global/Container";
import FormField from "@/components/FormField";
import Image from "next/image";

const PromptContainer = ({ data }) => {
  const [searchQuery, setSearchQuery] = useState("");
  const handleChange = (e) => setSearchQuery(e.target.value);

  const filteredData = (data, searchQuery) => {
    return data.filter((image) => {
      return (
        image.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        image.prompt.toLowerCase().includes(searchQuery.toLowerCase())
      );
    });
  };
  return (
    <div className="">
      <section className="bg-gray-800 pt-32 pb-28 text-white relative">
        <div className="absolute inset-0">
          <Image
            src={"/hero-2.jpg"}
            fill
            className="object-cover object-center"
          />
          <div className="absolute inset-0 bg-black/50"></div>
        </div>

        <Container className={"text-center relative z-10"}>
          <h1 className="font-bold   text-3xl sm:text-4xl">
            See the images generated by other people
          </h1>
          <p className="mt-4 text-gray-300  max-w-xl mx-auto">
            Browse through a collection of imaginative and visually stunning
            images using dalle-e api generated by random people in the internet
          </p>

          <div className="mt-5 max-w-2xl mx-auto">
            <FormField
              id={"name"}
              label={""}
              name={"name"}
              placeholder={"Search by prompt or name"}
              handleChange={handleChange}
              className={"text-white "}
              type="text"
              value={searchQuery}
            />
          </div>
        </Container>
      </section>
      <Container>
        <div className="py-16  grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
          {filteredData(data, searchQuery).map((image) => (
            <ImageCard
              key={image._id}
              _id={image._id}
              name={image.name}
              prompt={image.prompt}
              photo={image.photo}
            />
          ))}
        </div>
      </Container>
    </div>
  );
};

export default PromptContainer;
